### ISSUE TITLE
KohyaHiresTest image doesn't works

### ISSUE THREAD

**Issue by alexfredo** [tfm1102/ComfyUI-AnimateDiff-Colab#2]
Hi the workflow KohyaHiresTest image doesn't works when I drag and drop the picture on comfyui, please help ! https://github.com/tfm1102/ComfyUI-AnimateDiff-Colab/blob/main/special/KohyaHiresFix_Test/workflow_KohyaHiresTest_2048x1024.png

**Comment by tfm1102** [comment]
Thanks, try this one.
https://github.com/tfm1102/ComfyUI-AnimateDiff-Colab/blob/main/special/KohyaHiresFix_Test/workflow_KohyaHiresTest_2048x1024_rev.png
